# Generated by Django 2.0.2 on 2018-09-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['created', 'name'], 'verbose_name': 'compañía', 'verbose_name_plural': 'compañías'},
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='company',
            name='second_adress',
            field=models.TextField(verbose_name='Segunda Dirección'),
        ),
    ]
